#!/usr/bin/env node
/**
 * Emit mocks/tokens.css — the Phase 3 token system.
 *
 * Tier 1 (global) is the VERBATIM `palette.mjs` output. It is inlined by this
 * script rather than pasted by hand so that no hex value in the shipped token
 * file was ever typed by a human or a model: the only source of a colour
 * literal in this project is the generator.
 *
 * Tier 2 (alias) is derived from tier 1 with `color-mix(in oklab, …)` and
 * relative `oklch(from …)`. It exists because the generator's fixed lightness
 * spec (L_LIGHT = [0.993, 0.981, 0.956, 0.93, …]) has no step between 249 and
 * 241 mean-channel luminance, and the reference system needs a content field at
 * 244 that is simultaneously below fidelity.py's card threshold (>248) and
 * outside its band-detection window (239.5–242.5).
 *
 *   node mocks/build-tokens.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PALETTE = '/home/bewinxed/.claude/plugins/cache/rtd/design-for-ai/4.2.0/scripts/palette.mjs';
const ARGS = ['--seed', '263', '--chroma', 'muted', '--harmony', 'analogous', '--scheme', 'both'];

// palette.mjs exits 2 on a contrast miss but still prints the CSS, so stdout is
// read on any exit code and the code is reported rather than swallowed.
let out, code = 0;
try {
  out = execFileSync('node', [PALETTE, ...ARGS], { encoding: 'utf8' });
} catch (err) {
  out = err.stdout || '';
  code = err.status ?? 1;
  if (!out) throw err;
}
console.log(`palette.mjs exit=${code}  FAIL lines=${(out.match(/FAIL/g) || []).length}`);
writeFileSync(join(HERE, 'palette-263-muted-analogous.css'), out);

// Bridge the generator's selector to this project's Tailwind v4 `.dark` class
// variant. Without this the dark block is present in the file and never active.
const global = out
  .replace(/\n\/\* Contrast report[\s\S]*$/, '')
  .replace('[data-theme="dark"] {', '[data-theme="dark"],\n.dark {');

const report = (out.match(/\/\* Contrast report[\s\S]*$/) || [''])[0];

const css = `/* =============================================================================
   Cockpit — "Quiet Ledger" design tokens
   Generated by mocks/build-tokens.mjs. Do not edit by hand; edit the builder.

   TIER 1  global   verbatim palette.mjs output (the only source of hex here)
   TIER 2  alias    surfaces / inks / borders / status, derived with color-mix
   TIER 3  system   type, space, shape, elevation, motion

   palette.mjs --seed 263 --chroma muted --harmony analogous --scheme both
   ========================================================================== */

/* ------------------------------- TIER 1 ---------------------------------- */
${global.trim()}

/* ------------------------------- TIER 2 ----------------------------------
   Every value below resolves to a tier-1 step. Nothing is typed.

   Light is the primary ramp (user directive): the surface ladder is solved so
   the rendered result reproduces the comps' measured field / band / raised
   surfaces. Dark is re-solved against the dark lightness spec — the raised
   surface is a HIGHER step in dark, not an inversion of the light mapping.
   -------------------------------------------------------------------------- */
:root {
  /* surfaces — light: band 241 < field 245 < raised 253 */
  --surface-sunken:   var(--neutral-3);
  --surface-field:    color-mix(in oklab, var(--neutral-2), var(--neutral-3));
  --surface-raised:   var(--neutral-1);
  --surface-overlay:  var(--neutral-1);

  /* borders — graded, never flattened to one value (DW-3.14) */
  --border-hairline:  color-mix(in oklab, var(--neutral-4) 34%, var(--neutral-3));
  --border-divider:   color-mix(in oklab, var(--neutral-4) 72%, var(--neutral-3));
  --border-control:   var(--neutral-4);

  /* inks — a five-rung ladder inside the two tier-1 text steps */
  --ink-strong:  var(--neutral-12);
  --ink-row:     color-mix(in oklab, var(--neutral-12) 68%, var(--neutral-11));
  --ink-stat:    color-mix(in oklab, var(--neutral-12) 60%, var(--neutral-11));
  --ink-body:    color-mix(in oklab, var(--neutral-12) 46%, var(--neutral-11));
  --ink-muted:   var(--neutral-11);
  --ink-label:   color-mix(in oklab, var(--neutral-11) 74%, var(--neutral-12));

  /* the non-status accent of this DNA is graphite, not a hue */
  /* the focus ring is a token because it must clear 3:1 non-text contrast in
     BOTH schemes: --accent-solid measures 2.91:1 on the dark ground, so dark
     takes the light end of the accent ramp instead. */
  --focus-ring:  var(--accent-solid);
  --brand-solid: var(--neutral-12);
  --brand-hi:    oklch(from var(--neutral-12) calc(l + 0.075) c h);
  --brand-lo:    oklch(from var(--neutral-12) calc(l - 0.012) c h);
  --brand-edge:  oklch(from var(--neutral-12) calc(l - 0.045) c h);
  --on-brand:    var(--neutral-1);

  /* status — four functional hues, one meaning each, plus a hueless idle.
     The step-3 tints straight off the ramp are too pale to tell apart at pill
     size: measured CIEDE2000 between error-3 and warning-3 is 9.2, and between
     warning-3 and success-3 is 9.7. Pulling each tint 14% toward its own solid
     lifts the worst pair to 12.5 while keeping every text-on-tint pair at or
     above 4.7:1 — deepened rather than the threshold lowered. */
  --tint-depth: 86%;
  --status-live-bg:  color-mix(in oklab, var(--info-3)    var(--tint-depth), var(--info-9));
  --status-attn-bg:  color-mix(in oklab, var(--warning-3) var(--tint-depth), var(--warning-9));
  --status-done-bg:  color-mix(in oklab, var(--success-3) var(--tint-depth), var(--success-9));
  --status-fail-bg:  color-mix(in oklab, var(--error-3)   var(--tint-depth), var(--error-9));
  /* Idle carries NO fill. Measured: a hueless neutral-3 chip sits only 6.7
     CIEDE2000 from the live-blue chip in light and 6.4 in dark — a filled grey
     pill and a filled blue pill are not separable at this size. The comps solve
     it the same way (their .s-none rule is bare text), so idle is a label in muted
     ink with no pill at all: absence of a chip IS the idle state. */
  --status-idle-bg:  transparent;
  /* Inks are pulled toward the text extreme rather than used raw. Two measured
     reasons, neither visible to a token-level contrast check:
       - painted small text never reaches its nominal ink (11.5-13px at weight
         400-500 antialiases lighter), and
       - v3 composites the assistant scrim over the whole board, dimming
         everything behind it.
     Together those put seven pairs between 3.92:1 and 4.45:1 on the glass while
     every token-level pair read 4.7-5.5. Deepened here; the target was not moved. */
  --ink-depth: 52%;
  --status-live-ink: color-mix(in oklab, var(--info-11)    var(--ink-depth), var(--neutral-12));
  --status-attn-ink: color-mix(in oklab, var(--warning-11) var(--ink-depth), var(--neutral-12));
  --status-done-ink: color-mix(in oklab, var(--success-11) var(--ink-depth), var(--neutral-12));
  --status-fail-ink: color-mix(in oklab, var(--error-11)   var(--ink-depth), var(--neutral-12));
  --status-idle-ink: var(--neutral-11);

  /* elevation — hue-shifted cool graphite, never rgba(0,0,0,·) */
  --shadow-tint:   oklch(from var(--neutral-12) l c h / 0.055);
  --shadow-tint-2: oklch(from var(--neutral-12) l c h / 0.10);
  --shadow-tint-3: oklch(from var(--neutral-12) l c h / 0.16);
  --shadow-hairline: 0 1px 2px var(--shadow-tint);
  --shadow-tile:     0 1px 2.5px var(--shadow-tint-2), 0 0 0 .5px var(--shadow-tint);
  --shadow-lifted:   0 6px 18px var(--shadow-tint-2), 0 1px 3px var(--shadow-tint);
  --shadow-overlay:  0 18px 48px var(--shadow-tint-3), 0 2px 6px var(--shadow-tint);
  --shadow-drawer:   0 12px 40px var(--shadow-tint-3);
  --shadow-inset-sel: inset 0 1px 1px var(--shadow-tint);
  --shadow-action:   inset 0 -1px 0 var(--brand-edge), 0 1px 2px var(--shadow-tint-2);

  /* the signature move, as tokens: the action is never flat, and the item mark
     carries the same top-light/bottom-shade read at 17px */
  --gradient-action: linear-gradient(var(--brand-hi), var(--brand-lo));
  --mark-overlay:    linear-gradient(oklch(from var(--neutral-1) l c h / 0.22),
                                     oklch(from var(--neutral-12) l c h / 0.06));
  --scrim:      oklch(from var(--neutral-12) l c h / 0.32);
  --scrim-soft: oklch(from var(--neutral-12) l c h / 0.06);
}

[data-theme="dark"],
.dark {
  /* dark is re-solved, not inverted: raised climbs the ramp instead of falling */
  --surface-sunken:   var(--neutral-1);
  --surface-field:    var(--neutral-2);
  --surface-raised:   var(--neutral-3);
  --surface-overlay:  var(--neutral-4);

  --border-hairline:  color-mix(in oklab, var(--neutral-5) 40%, var(--neutral-4));
  --border-divider:   color-mix(in oklab, var(--neutral-5) 75%, var(--neutral-4));
  --border-control:   var(--neutral-6);

  --ink-strong:  var(--neutral-12);
  --ink-row:     color-mix(in oklab, var(--neutral-12) 88%, var(--neutral-11));
  --ink-stat:    color-mix(in oklab, var(--neutral-12) 72%, var(--neutral-11));
  --ink-body:    color-mix(in oklab, var(--neutral-12) 30%, var(--neutral-11));
  --ink-muted:   var(--neutral-11);
  --ink-label:   color-mix(in oklab, var(--neutral-11) 88%, var(--neutral-10));

  --focus-ring:  var(--accent-11);
  --brand-solid: var(--neutral-12);
  --brand-hi:    oklch(from var(--neutral-12) calc(l - 0.02) c h);
  --brand-lo:    oklch(from var(--neutral-12) calc(l + 0.02) c h);
  --brand-edge:  oklch(from var(--neutral-12) calc(l + 0.05) c h);
  --on-brand:    var(--neutral-1);

  --status-idle-bg: transparent;       --status-idle-ink: var(--neutral-11);

  --shadow-tint:   oklch(from var(--neutral-1) l c h / 0.55);
  --shadow-tint-2: oklch(from var(--neutral-1) l c h / 0.66);
  --shadow-tint-3: oklch(from var(--neutral-1) l c h / 0.76);
  --scrim:      oklch(from var(--neutral-1) l c h / 0.60);
  --scrim-soft: oklch(from var(--neutral-1) l c h / 0.30);
}

/* ------------------------------- TIER 3 ----------------------------------
   Type, space, shape, motion. Deliberately NOT shadcn's generated defaults —
   "unmodified shadcn defaults" is a binary High-severity tell.
   -------------------------------------------------------------------------- */
:root {
  /* type — one superfamily, two roles. Ratio 1.125 from a 13px base, the size
     the ledger-grid's dominant element (the table row name) is actually set at,
     rounded to the nearest 0.25px. */
  --font-body:    'Geist Variable', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif;
  --font-display: var(--font-body);
  --font-mono:    'Geist Mono Variable', ui-monospace, 'SF Mono', Menlo, monospace;

  /* rem, not px. Measured: with a px scale, a user asking their browser for
     200% text moved nothing at all — the stat value stayed 23.5px. These are
     the same nine steps expressed against a 16px root, so the default render is
     unchanged to the pixel, and a text-size preference now scales the whole
     system. (WCAG 2.2 SC 1.4.4 Resize Text.) */
  --text-xs:   0.640625rem;  /* 10.25px */
  --text-sm:   0.71875rem;   /* 11.5px  */
  --text-base: 0.8125rem;    /* 13px    */
  --text-md:   0.90625rem;   /* 14.5px  */
  --text-lg:   1.03125rem;   /* 16.5px  */
  --text-xl:   1.15625rem;   /* 18.5px  */
  --text-2xl:  1.296875rem;  /* 20.75px */
  --text-3xl:  1.46875rem;   /* 23.5px  */
  --text-4xl:  1.640625rem;  /* 26.25px */

  --leading-tight: 1.2;    /* display, stat values */
  --leading-body:  1.4;    /* body copy — inside the 1.2–1.4 constraint */
  --leading-ui:    1.25;   /* single-line controls and rows */
  --leading-numeric: 1;    /* display figures: digits carry no descender, and a
                              body line box on a 23.5px value overflows the
                              measured 90px stat card and clips the KPI */

  --weight-body:   400;
  --weight-medium: 450;
  --weight-strong: 500;    /* 600 and above never appear — see ## Type */

  --track-display: -0.008em;
  --track-body:     0em;
  --track-caps:     0.01em;

  /* space — measured off the comps, deliberately not a 4px multiple ladder */
  --space-1:  4px;
  --space-2:  7px;    /* stat-well inset */
  --space-3: 11px;    /* table-card padding */
  --space-4: 14px;    /* stat-card gap */
  --space-5: 18px;
  --space-6: 21px;    /* content padding, right */
  --space-7: 25px;    /* content padding, left — the asymmetry is the point */
  --space-8: 32px;

  /* shape — six measured radii, none of them shadcn's 4/6/8/12 ladder */
  --radius:        10px;   /* the base: the stat card */
  --radius-mark:   4.6px;
  --radius-tile:   5.5px;
  --radius-well:   7px;
  --radius-control: 8px;
  --radius-card:   10px;
  --radius-panel:  14px;
  --radius-pill:   999px;

  /* motion — the one unpinned DNA axis. Structure never moves; only the live
     channel does. */
  --motion-instant: 0ms;
  --motion-fast:   120ms;
  --motion-base:   200ms;
  --motion-slow:   320ms;
  --ease-entry:  cubic-bezier(0.16, 1, 0.3, 1);
  --ease-exit:   cubic-bezier(0.7, 0, 0.84, 0);
  --ease-toggle: cubic-bezier(0.65, 0, 0.35, 1);
  --breath: 2000ms;
}

@media (prefers-reduced-motion: reduce) {
  :root { --motion-fast: 0ms; --motion-base: 0ms; --motion-slow: 0ms; --breath: 0ms; }
  *, *::before, *::after {
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 1ms !important;
  }
}

${report.trim()}
`;

writeFileSync(join(HERE, 'tokens.css'), css);
console.log(`WROTE mocks/tokens.css (${css.length} bytes)`);
