#!/usr/bin/env node
import { execFileSync } from "node:child_process";
/**
 * Emit mocks/tokens.css — the Phase 3 token system.
 *
 * Tier 1 (global) is the VERBATIM `palette.mjs` output. It is inlined by this
 * script rather than pasted by hand so that no hex value in the shipped token
 * file was ever typed by a human or a model: the only source of a colour
 * literal in this project is the generator.
 *
 * Tier 2 (alias) is derived from tier 1 with `color-mix(in oklab, …)` and
 * relative `oklch(from …)`. It exists because the generator's fixed lightness
 * spec (L_LIGHT = [0.993, 0.981, 0.956, 0.93, …]) has no step between 249 and
 * 241 mean-channel luminance, and the reference system needs a content field at
 * 244 that is simultaneously below fidelity.py's card threshold (>248) and
 * outside its band-detection window (239.5–242.5).
 *
 *   node mocks/build-tokens.mjs
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PALETTE =
  "/home/bewinxed/.claude/plugins/cache/rtd/design-for-ai/4.2.0/scripts/palette.mjs";
const ARGS = [
  "--seed",
  "263",
  "--chroma",
  "muted",
  "--harmony",
  "analogous",
  "--scheme",
  "both",
];

// palette.mjs exits 2 on a contrast miss but still prints the CSS, so stdout is
// read on any exit code and the code is reported rather than swallowed.
let out,
  code = 0;
try {
  out = execFileSync("node", [PALETTE, ...ARGS], { encoding: "utf8" });
} catch (err) {
  out = err.stdout || "";
  code = err.status ?? 1;
  if (!out) {
    throw err;
  }
}
console.log(
  `palette.mjs exit=${code}  FAIL lines=${(out.match(/FAIL/g) || []).length}`
);
writeFileSync(join(HERE, "palette-263-muted-analogous.css"), out);

// Bridge the generator's selector to this project's Tailwind v4 `.dark` class
// variant. Without this the dark block is present in the file and never active.
const global = out
  .replace(/\n\/\* Contrast report[\s\S]*$/, "")
  .replace('[data-theme="dark"] {', '[data-theme="dark"],\n.dark {');

const report = (out.match(/\/\* Contrast report[\s\S]*$/) || [""])[0];

const css = `/* =============================================================================
   Whiffle — "Quiet Ledger" design tokens
   Generated by mocks/build-tokens.mjs. Do not edit by hand; edit the builder.

   TIER 1  global   verbatim palette.mjs output (the only source of hex here)
   TIER 2  alias    surfaces / inks / borders / status, derived with color-mix
   TIER 3  system   type, space, shape, elevation, motion

   palette.mjs --seed 263 --chroma muted --harmony analogous --scheme both
   ========================================================================== */

/* ------------------------------- TIER 1 ---------------------------------- */
${global.trim()}

/* ------------------------------- TIER 2 ----------------------------------
   Every value below resolves to a tier-1 step. Nothing is typed.

   Light is the primary ramp (user directive): the surface ladder is solved so
   the rendered result reproduces the comps' measured field / band / raised
   surfaces. Dark is re-solved against the dark lightness spec — the raised
   surface is a HIGHER step in dark, not an inversion of the light mapping.
   -------------------------------------------------------------------------- */
:root {
  /* surfaces — light: band 241 < field 245 < raised 253 */
  --surface-sunken:   var(--neutral-3);
  --surface-field:    color-mix(in oklab, var(--neutral-2), var(--neutral-3));
  --surface-raised:   var(--neutral-1);
  --surface-overlay:  var(--neutral-1);

  /* borders — graded, never flattened to one value (DW-3.14) */
  --border-hairline:  color-mix(in oklab, var(--neutral-4) 34%, var(--neutral-3));
  --border-divider:   color-mix(in oklab, var(--neutral-4) 72%, var(--neutral-3));
  --border-control:   var(--neutral-4);

  /* inks — a five-rung ladder inside the two tier-1 text steps */
  --ink-strong:  var(--neutral-12);
  --ink-row:     color-mix(in oklab, var(--neutral-12) 68%, var(--neutral-11));
  --ink-stat:    color-mix(in oklab, var(--neutral-12) 60%, var(--neutral-11));
  --ink-body:    color-mix(in oklab, var(--neutral-12) 46%, var(--neutral-11));
  --ink-muted:   var(--neutral-11);
  --ink-label:   color-mix(in oklab, var(--neutral-11) 74%, var(--neutral-12));

  /* the non-status accent of this DNA is graphite, not a hue */
  /* the focus ring is a token because it must clear 3:1 non-text contrast in
     BOTH schemes: --accent-solid measures 2.91:1 on the dark ground, so dark
     takes the light end of the accent ramp instead. */
  --focus-ring:  var(--accent-solid);
  --brand-solid: var(--neutral-12);
  --brand-hi:    oklch(from var(--neutral-12) calc(l + 0.075) c h);
  --brand-lo:    oklch(from var(--neutral-12) calc(l - 0.012) c h);
  --brand-edge:  oklch(from var(--neutral-12) calc(l - 0.045) c h);
  --on-brand:    var(--neutral-1);

  /* ---- Flexoki v2 accent swatches (user directive) ----------------------
     The functional hues — and only the functional/identity hues — are migrated
     to Flexoki v2's accents (oklch canonical). The NEUTRAL graphite ramp is
     untouched; the accent ramp / focus ring / brand are left as the generator
     solved them. error->red, success->green, warning->yellow, info->blue.
     Only the three steps the status aliases and data colours consume are
     overridden (-3 pale tint, -9 solid, -11 ink). Inks take the 850 step so the
     dark text clears 4.5:1 on the pale-100 chip, not only on white. */
  --error-3:    oklch(88.2% .064 36.4);   /* red-100    */
  --error-9:    oklch(50.4% .165 27.8);   /* red-600    */
  --error-11:   oklch(31.3% .087 26.3);   /* red-850    */
  --warning-3:  oklch(91.4% .087 93.2);   /* yellow-100 */
  --warning-9:  oklch(63.3% .129 85.8);   /* yellow-600 */
  --warning-11: oklch(37.0% .074 88.4);   /* yellow-850 */
  /* done takes the 200-step green base (more chroma) rather than the 100: the
     pale yellow attn-tint and a pale green done-tint sit only 35deg apart and
     collide at pill size on the 100 step; a more saturated green clears >=12. */
  --success-3:  oklch(81.0% .098 115.5);  /* green-200  */
  --success-9:  oklch(55.9% .134 122.9);  /* green-600  */
  --success-11: oklch(33.8% .076 121.9);  /* green-850  */
  --info-3:     oklch(88.4% .029 228.1);  /* blue-100   */
  --info-9:     oklch(48.2% .131 254.8);  /* blue-600   */
  --info-11:    oklch(30.6% .069 253.5);  /* blue-850   */

  /* status — four functional hues, one meaning each, plus a hueless idle.
     The step-3 tints straight off the ramp are too pale to tell apart at pill
     size: measured CIEDE2000 between error-3 and warning-3 is 9.2, and between
     warning-3 and success-3 is 9.7. Pulling each tint 14% toward its own solid
     lifts the worst pair to 12.5 while keeping every text-on-tint pair at or
     above 4.7:1 — deepened rather than the threshold lowered. */
  --tint-depth: 76%;
  --status-live-bg:  color-mix(in oklab, var(--info-3)    var(--tint-depth), var(--info-9));
  --status-attn-bg:  color-mix(in oklab, var(--warning-3) var(--tint-depth), var(--warning-9));
  --status-done-bg:  color-mix(in oklab, var(--success-3) var(--tint-depth), var(--success-9));
  --status-fail-bg:  color-mix(in oklab, var(--error-3)   var(--tint-depth), var(--error-9));
  /* Idle carries NO fill. Measured: a hueless neutral-3 chip sits only 6.7
     CIEDE2000 from the live-blue chip in light and 6.4 in dark — a filled grey
     pill and a filled blue pill are not separable at this size. The comps solve
     it the same way (their .s-none rule is bare text), so idle is a label in muted
     ink with no pill at all: absence of a chip IS the idle state. */
  --status-idle-bg:  transparent;
  /* Inks are pulled toward the text extreme rather than used raw. Two measured
     reasons, neither visible to a token-level contrast check:
       - painted small text never reaches its nominal ink (11.5-13px at weight
         400-500 antialiases lighter), and
       - v3 composites the assistant scrim over the whole board, dimming
         everything behind it.
     Together those put seven pairs between 3.92:1 and 4.45:1 on the glass while
     every token-level pair read 4.7-5.5. Deepened here; the target was not moved. */
  --ink-depth: 76%;
  --status-live-ink: color-mix(in oklab, var(--info-11)    var(--ink-depth), var(--neutral-12));
  --status-attn-ink: color-mix(in oklab, var(--warning-11) var(--ink-depth), var(--neutral-12));
  --status-done-ink: color-mix(in oklab, var(--success-11) var(--ink-depth), var(--neutral-12));
  --status-fail-ink: color-mix(in oklab, var(--error-11)   var(--ink-depth), var(--neutral-12));
  --status-idle-ink: var(--neutral-11);

  /* ---- data colour ------------------------------------------------------
     The reference colours its Success column by value — green, amber, red — and
     that is information, not decoration, on a console whose job is showing what
     needs attention. Threshold numerals were riding the muted 11-step through
     the ink-depth correction and came out near-grey (measured rgb(94,84,64) for
     an amber value). These take the SOLID hue darkened, so chroma survives. */
  --data-ok:   oklch(from var(--success-9) 0.46 0.125 h);
  --data-warn: oklch(from var(--warning-9) 0.46 0.125 h);
  --data-bad:  oklch(from var(--error-9)   0.46 0.135 h);

  /* ---- CHART PALETTE — Okabe-Ito categorical (colour-blind safe) ---------
     Phase 6 (DW-6.9): the chart palette is chosen by DATA TYPE, NOT the brand
     palette — the two are explicitly not the same set. This is Okabe-Ito's
     8-colour categorical set, the canonical colour-blind-safe default, taken
     verbatim from the published hex and re-expressed in OKLCH (light scheme).
     It is deliberately distinct from the four STATUS hues (DW-6.6): the status
     red/amber/green appear ONLY on status indicators; these are the categorical
     hues a chart may use. Every series using them carries a redundant non-hue
     channel (pattern / direct label) so it survives deuteranopia/protanopia.
     Okabe, I. & Ito, K., "Colour Universal Design", 2008. */
  --chart-1: oklch(0.753 0.158 76.8);   /* #E69F00 orange   */
  --chart-2: oklch(0.735 0.117 236.2);  /* #56B4E9 sky blue */
  --chart-3: oklch(0.620 0.130 165.5);  /* #009E73 green    */
  --chart-4: oklch(0.902 0.172 105.0);  /* #F0E442 yellow   */
  --chart-5: oklch(0.532 0.131 244.0);  /* #0072B2 blue     */
  --chart-6: oklch(0.621 0.170 47.5);   /* #D55E00 vermillion */
  --chart-7: oklch(0.679 0.118 346.3);  /* #CC79A7 purple   */
  --chart-8: oklch(0.000 0.000 0.0);    /* #000000 black    */

  /* elevation — hue-shifted cool graphite, never rgba(0,0,0,·) */
  /* Elevation was too faint to register: at 0.055 alpha over a 1px blur the
     cards melted into the canvas and the whole board read as one flat grey. The
     tint stays cool graphite (neutral-12, never pure black — DW-3.10); only the
     alpha and the spread grow, to reference-level lift — a soft drop, not a
     heavy AI-tell shadow. */
  --shadow-tint:   oklch(from var(--neutral-12) l c h / 0.09);
  --shadow-tint-2: oklch(from var(--neutral-12) l c h / 0.14);
  --shadow-tint-3: oklch(from var(--neutral-12) l c h / 0.20);
  --shadow-hairline: 0 3px 7px -2px var(--shadow-tint-2);
  --shadow-tile:     0 2px 6px var(--shadow-tint-2), 0 0 0 .5px var(--shadow-tint);
  --shadow-lifted:   0 6px 18px var(--shadow-tint-2), 0 1px 3px var(--shadow-tint);
  --shadow-overlay:  0 18px 48px var(--shadow-tint-3), 0 2px 6px var(--shadow-tint);
  --shadow-drawer:   0 12px 40px var(--shadow-tint-3);
  --shadow-inset-sel: inset 0 1px 1px var(--shadow-tint);
  --shadow-action:   inset 0 -1px 0 var(--brand-edge), 0 1px 2px var(--shadow-tint-2);

  /* ---- identity palette for item marks ---------------------------------
     The user's constraint names small marks as a place colour LIVES: "colour
     lives on chips, badges, and small marks". The marks had gone graphite
     because DW-3.12 asked for a non-status accent distinct from the four
     functional hues and no single hue satisfied that plus the contrast floor —
     but the constraint is NON-COLLISION, not absence, and one hue was the wrong
     shape of answer. Six identity hues, rotated off the accent in OKLCH so they
     are token-derived rather than typed, all at one lightness and chroma so a
     white glyph clears contrast on every one of them.

     They do not collide with status because they differ in FORM as well as hue:
     status is a pale tint carrying dark ink, an item mark is a saturated solid
     carrying a white glyph. Separation is measured in colorcheck.py. */
  /* Light marks were L*0.50 / C0.155 and read as dark, muddy squares against the
     near-white sidebar — legible glyph, but heavy identity. Lifted to L*0.56 and
     saturated to C0.165 so each mark reads as a vivid identity colour; the white
     glyph still clears 4.5:1 on every one (measured), and dark is untouched. */
  /* Eight identity hues drawn from Flexoki's eight accents (richer than the six
     rotations that came before). The lightness is held near L*0.51 rather than
     taken raw from Flexoki's 400–600 steps: the light hues (yellow/green/cyan)
     are too bright at their own lightness for a white glyph to clear 4.5:1, so
     each Flexoki HUE is placed on a common dark-enough lightness. The white
     glyph clears 4.5:1 on every one (measured in colorcheck / the crops). */
  --mark-1: oklch(0.51 0.168 27.9);    /* red     */
  --mark-2: oklch(0.53 0.150 47.4);    /* orange  */
  --mark-3: oklch(0.50 0.115 86.8);    /* yellow  */
  --mark-4: oklch(0.51 0.132 121.2);   /* green   */
  --mark-5: oklch(0.51 0.093 186.7);   /* cyan    */
  --mark-6: oklch(0.51 0.140 251.4);   /* blue    */
  --mark-7: oklch(0.51 0.150 292.5);   /* purple  */
  --mark-8: oklch(0.51 0.165 349.8);   /* magenta */
  --mark-glyph: oklch(from var(--neutral-1) 0.99 0 h);

  /* the signature move, as tokens: the action is never flat, and the item mark
     carries the same top-light/bottom-shade read at 17px */
  --gradient-action: linear-gradient(var(--brand-hi), var(--brand-lo));
  --mark-overlay:    linear-gradient(oklch(from var(--neutral-1) l c h / 0.22),
                                     oklch(from var(--neutral-12) l c h / 0.06));
  --scrim:      oklch(from var(--neutral-12) l c h / 0.32);
  --scrim-soft: oklch(from var(--neutral-12) l c h / 0.06);

  /* Tool/think/branch left rail. A flat 1px hairline at --border-hairline
     (#EDEDED on the #F4F4F4 field) measured ~1.0:1 against the surface — an
     invisible rail. This is a vertical gradient instead: stronger at the top
     (the active end, where the group begins) and fading down, drawn from the
     muted ink at low alpha so it reads on both schemes without going heavy. */
  --rail: linear-gradient(oklch(from var(--neutral-11) l c h / 0.58),
                          oklch(from var(--neutral-11) l c h / 0.06));
}

[data-theme="dark"],
.dark {
  /* dark is re-solved, not inverted: raised climbs the ramp instead of falling */
  --surface-sunken:   var(--neutral-1);
  --surface-field:    var(--neutral-2);
  --surface-raised:   var(--neutral-3);
  --surface-overlay:  var(--neutral-4);

  --border-hairline:  color-mix(in oklab, var(--neutral-5) 40%, var(--neutral-4));
  --border-divider:   color-mix(in oklab, var(--neutral-5) 75%, var(--neutral-4));
  --border-control:   var(--neutral-6);

  --ink-strong:  var(--neutral-12);
  --ink-row:     color-mix(in oklab, var(--neutral-12) 88%, var(--neutral-11));
  --ink-stat:    color-mix(in oklab, var(--neutral-12) 72%, var(--neutral-11));
  --ink-body:    color-mix(in oklab, var(--neutral-12) 30%, var(--neutral-11));
  --ink-muted:   var(--neutral-11);
  --ink-label:   color-mix(in oklab, var(--neutral-11) 88%, var(--neutral-10));

  --focus-ring:  var(--accent-11);
  --brand-solid: var(--neutral-12);
  --brand-hi:    oklch(from var(--neutral-12) calc(l - 0.02) c h);
  --brand-lo:    oklch(from var(--neutral-12) calc(l + 0.02) c h);
  --brand-edge:  oklch(from var(--neutral-12) calc(l + 0.05) c h);
  --on-brand:    var(--neutral-1);

  /* Flexoki accents, dark: the steps mirror — a deep 850 becomes the chip-fill
     base and a pale 200 becomes the ink, so the same alias formula that deepens
     the light chip lifts the dark one. Solid (-9) stays the 500 step for data. */
  --error-3:    oklch(31.3% .087 26.3);   /* red-850    */
  --error-9:    oklch(55.0% .168 27.9);   /* red-500    */
  --error-11:   oklch(88.2% .064 36.4);   /* red-100    */
  --warning-3:  oklch(37.0% .074 88.4);   /* yellow-850 */
  --warning-9:  oklch(68.3% .138 86.8);   /* yellow-500 */
  --warning-11: oklch(85.0% .131 92.3);   /* yellow-200 */
  --success-3:  oklch(33.8% .076 121.9);  /* green-850  */
  --success-9:  oklch(60.5% .132 121.2);  /* green-500  */
  --success-11: oklch(81.0% .098 115.5);  /* green-200  */
  --info-3:     oklch(30.6% .069 253.5);  /* blue-850   */
  --info-9:     oklch(53.9% .121 251.4);  /* blue-500   */
  --info-11:    oklch(78.2% .062 235.9);  /* blue-200   */
  /* dark chips mix in more solid than light: two deep 850 tints (yellow, red)
     are near-identical browns at the light scheme's depth, so the dark scheme
     carries more chroma to hold them apart while staying deep enough for the
     pale ink to clear 4.5:1. */
  --tint-depth: 76%;
  /* attn (yellow) and fail (red) are near-identical deep browns at the shared
     depth; each carries a little more of its own solid so the yellow<->red hue
     gap registers (>=12 dE between the two chips) while live/done stay deep for
     the identity-mark separation. */
  --status-attn-bg: color-mix(in oklab, var(--warning-3) 68%, var(--warning-9));
  --status-fail-bg: color-mix(in oklab, var(--error-3) 68%, var(--error-9));

  --status-idle-bg: transparent;       --status-idle-ink: var(--neutral-11);
  --data-ok:   oklch(from var(--success-9) 0.78 0.135 h);
  --data-warn: oklch(from var(--warning-9) 0.80 0.130 h);
  --data-bad:  oklch(from var(--error-9)   0.81 0.130 h);

  /* CHART PALETTE, dark — the same Okabe-Ito categorical set, re-solved so it
     reads on the dark ground. Only the foreground-weak colours change: the
     categorical "black" cannot paint on a dark field, so it becomes a light
     neutral; the mid blue is lifted a step. Hue identity is preserved so the
     CVD-safe separation holds in both schemes. */
  --chart-1: oklch(0.780 0.160 76.8);   /* orange   */
  --chart-2: oklch(0.770 0.120 236.2);  /* sky blue */
  --chart-3: oklch(0.660 0.135 165.5);  /* green    */
  --chart-4: oklch(0.920 0.150 105.0);  /* yellow   */
  --chart-5: oklch(0.620 0.135 244.0);  /* blue     */
  --chart-6: oklch(0.680 0.175 47.5);   /* vermillion */
  --chart-7: oklch(0.720 0.125 346.3);  /* purple   */
  --chart-8: oklch(0.930 0.000 0.0);    /* black -> light graphite on dark */

  /* identity marks lift on a dark ground — L*0.70, one step above the deep
     status chips (L*~0.30). Four of the eight Flexoki hues (red/yellow/green/
     blue) are shared with the status chips, so the identity mark and its
     same-hue chip separate on lightness; the lift takes every mark-vs-status
     pair above 25 dE. */
  --mark-1: oklch(0.70 0.170 27.9);    /* red     */
  --mark-2: oklch(0.70 0.150 47.4);    /* orange  */
  --mark-3: oklch(0.70 0.120 86.8);    /* yellow  */
  --mark-4: oklch(0.70 0.135 121.2);   /* green   */
  --mark-5: oklch(0.70 0.095 186.7);   /* cyan    */
  --mark-6: oklch(0.70 0.145 251.4);   /* blue    */
  --mark-7: oklch(0.70 0.155 292.5);   /* purple  */
  --mark-8: oklch(0.70 0.170 349.8);   /* magenta */

  --shadow-tint:   oklch(from var(--neutral-1) l c h / 0.55);
  --shadow-tint-2: oklch(from var(--neutral-1) l c h / 0.66);
  --shadow-tint-3: oklch(from var(--neutral-1) l c h / 0.76);
  --scrim:      oklch(from var(--neutral-1) l c h / 0.60);
  --scrim-soft: oklch(from var(--neutral-1) l c h / 0.30);
  /* on the dark field the rail needs a touch more presence to stay legible */
  --rail: linear-gradient(oklch(from var(--neutral-11) l c h / 0.55),
                          oklch(from var(--neutral-11) l c h / 0.08));
}

/* ------------------------------- TIER 3 ----------------------------------
   Type, space, shape, motion. Deliberately NOT shadcn's generated defaults —
   "unmodified shadcn defaults" is a binary High-severity tell.
   -------------------------------------------------------------------------- */
:root {
  /* type — one superfamily, two roles. Ratio 1.125 from a 13px base, the size
     the ledger-grid's dominant element (the table row name) is actually set at,
     rounded to the nearest 0.25px. */
  --font-body:    'Geist Variable', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif;
  --font-display: var(--font-body);
  --font-mono:    'Geist Mono Variable', ui-monospace, 'SF Mono', Menlo, monospace;

  /* rem, not px. Measured: with a px scale, a user asking their browser for
     200% text moved nothing at all — the stat value stayed 23.5px. These are
     the same nine steps expressed against a 16px root, so the default render is
     unchanged to the pixel, and a text-size preference now scales the whole
     system. (WCAG 2.2 SC 1.4.4 Resize Text.) */
  --text-xs:   0.640625rem;  /* 10.25px */
  --text-sm:   0.71875rem;   /* 11.5px  */
  --text-base: 0.8125rem;    /* 13px    */
  --text-md:   0.90625rem;   /* 14.5px  */
  --text-lg:   1.03125rem;   /* 16.5px  */
  --text-xl:   1.15625rem;   /* 18.5px  */
  --text-2xl:  1.296875rem;  /* 20.75px */
  --text-3xl:  1.46875rem;   /* 23.5px  */
  --text-4xl:  1.640625rem;  /* 26.25px */

  --leading-tight: 1.2;    /* display, stat values */
  --leading-body:  1.4;    /* body copy — inside the 1.2–1.4 constraint */
  --leading-ui:    1.25;   /* single-line controls and rows */
  --leading-numeric: 1;    /* display figures: digits carry no descender, and a
                              body line box on a 23.5px value overflows the
                              measured 90px stat card and clips the KPI */

  --weight-body:   400;
  --weight-medium: 450;
  --weight-strong: 500;    /* 600 and above never appear — see ## Type */

  --track-display: -0.008em;
  --track-body:     0em;
  --track-caps:     0.01em;

  /* space — measured off the comps, deliberately not a 4px multiple ladder */
  --space-1:  4px;
  --space-2:  7px;    /* stat-well inset */
  --space-3: 11px;    /* table-card padding */
  --space-4: 14px;    /* stat-card gap */
  --space-5: 18px;
  --space-6: 21px;    /* content padding, right */
  --space-7: 25px;    /* content padding, left — the asymmetry is the point */
  --space-8: 32px;

  /* shape — six measured radii, none of them shadcn's 4/6/8/12 ladder */
  --radius:        10px;   /* the base: the stat card */
  --radius-mark:   4.6px;
  --radius-tile:   5.5px;
  --radius-well:   7px;
  --radius-control: 8px;
  --radius-card:   10px;
  --radius-modal:  12px;   /* modal control groups (fields / footer buttons) */
  --radius-panel:  14px;
  --radius-shell:  20px;   /* floating shell surfaces (composer, modal frame) */
  --radius-pill:   999px;

  /* motion — the one unpinned DNA axis. Structure never moves; only the live
     channel does.
     A SINGLE vocabulary: the component tier's 100 / 300 / 500ms durations are
     canonical here (--c-100 / --c-300 / --c-500), and the earlier --motion-*
     aliases resolve through them, so the two names can never drift apart.
     Easings are limited to the three canonical curves (--e-in / --e-out /
     --e-toggle); instance use is var(--e-in) for entry and var(--e-out) for
     exit, with --e-toggle reserved for continuous toggles. */
  --c-100:100ms; --c-300:300ms; --c-500:500ms;
  --e-in:    cubic-bezier(0.16, 1, 0.3, 1);
  --e-out:   cubic-bezier(0.7, 0, 0.84, 0);
  --e-toggle: cubic-bezier(0.65, 0, 0.35, 1);
  --motion-instant: 0ms;
  --motion-fast:   var(--c-100);
  --motion-base:   var(--c-300);
  --motion-slow:   var(--c-500);
  --breath: calc(var(--c-500) * 4);   /* 2000ms — the running mark's breath */
  --ease-entry:  var(--e-in);
  --ease-exit:   var(--e-out);
  --ease-toggle: var(--e-toggle);
}

@media (prefers-reduced-motion: reduce) {
  :root { --motion-instant: 0ms; --motion-fast: 0ms; --motion-base: 0ms; --motion-slow: 0ms; --breath: 0ms; }
  *, *::before, *::after {
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 1ms !important;
  }
}

${report.trim()}
`;

writeFileSync(join(HERE, "tokens.css"), css);
console.log(`WROTE mocks/tokens.css (${css.length} bytes)`);
