#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
/**
 * Resolve every colour token in mocks/tokens.css to a concrete sRGB hex, in BOTH
 * schemes, by asking the browser.
 *
 * Two things make the naive version silently return nothing, and both are worth
 * recording because each looks like success:
 *
 *  1. `getComputedStyle().getPropertyValue('--x')` returns the *specified* value
 *     — it hands back the literal string "color-mix(in oklab, …)" and proves
 *     nothing. So each token is assigned to a probe element's `color` and read
 *     back from the computed style instead.
 *  2. A file:// stylesheet is an opaque origin: `document.styleSheets[0].cssRules`
 *     throws SecurityError, so enumerating token names from inside the page
 *     yields an EMPTY set and a clean "0 tokens" run. Names are therefore parsed
 *     from the CSS text in node and passed in.
 *
 * Chrome computes color-mix/oklch to `oklab(…)`/`oklch(…)`, not `rgb(…)`, so the
 * final sRGB byte values are taken by painting each computed colour onto a 1x1
 * canvas and reading the pixel — the same conversion the renderer performs.
 *
 *   node mocks/resolve-tokens.mjs   ->  mocks/tokens.resolved.css
 */
import { chromium } from "playwright-core";

const HERE = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(HERE, "tokens.css"), "utf8");
const names = [
  ...new Set(
    source.replace(/\/\*[\s\S]*?\*\//g, "").match(/--[\w-]+(?=\s*:)/g) || []
  ),
].sort();

const browser = await chromium.launch({
  executablePath:
    process.env.CHROMIUM_BIN ||
    "/home/bewinxed/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome",
  headless: true,
  args: ["--no-sandbox", "--disable-gpu", "--force-color-profile=srgb"],
});
const page = await browser.newPage();
writeFileSync(
  join(HERE, ".probe.html"),
  '<!doctype html><link rel="stylesheet" href="./tokens.css">' +
    '<div id="sentinel"><div id="probe"></div></div>'
);
await page.goto(pathToFileURL(join(HERE, ".probe.html")).href, {
  waitUntil: "load",
});

const dump = async (dark) =>
  page.evaluate(
    ({ isDark, names }) => {
      document.documentElement.classList.toggle("dark", isDark);
      const probe = document.getElementById("probe");
      const cv = document.createElement("canvas");
      cv.width = cv.height = 1;
      const ctx = cv.getContext("2d", { willReadFrequently: true });
      const out = {};
      const skipped = [];
      for (const n of names) {
        // ONLY COLOUR TOKENS. Assigning a duration, a font stack, a length or a
        // composite shadow to `color` is invalid, so the property keeps its
        // inherited value and the token is recorded as #000000. That put 114 fake
        // black entries in this file — including every shadow token, the exact
        // value `## Never` #6 bans — which reads as a design defect that does not
        // exist. Probe against a sentinel instead: if the declaration is rejected,
        // the sentinel survives and the token is not a colour.
        // `color` INHERITS, and a var() that is invalid at computed-value time falls
        // back to the inherited value — not to any previous inline value, which is
        // why an inline sentinel gets wiped. So the sentinel lives on the parent.
        probe.parentElement.style.color = "rgb(1, 2, 3)";
        probe.style.color = `var(${n})`;
        const c = getComputedStyle(probe).color;
        if (!c || c === "rgb(1, 2, 3)") {
          skipped.push(n);
          continue;
        }
        ctx.clearRect(0, 0, 1, 1);
        ctx.fillStyle = "#000";
        try {
          ctx.fillStyle = c;
        } catch {
          continue;
        }
        ctx.fillRect(0, 0, 1, 1);
        const [r, g, b, a] = ctx.getImageData(0, 0, 1, 1).data;
        if (a < 250) {
          continue; // alpha tokens are not inks
        }
        out[n] =
          `#${[r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
      }
      return { out, skipped };
    },
    { isDark: dark, names }
  );

const lightR = await dump(false);
const darkR = await dump(true);
const light = lightR.out,
  dark = darkR.out;
await browser.close();

const block = (sel, obj) =>
  `${sel} {\n` +
  Object.entries(obj)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n") +
  "\n}\n";

writeFileSync(
  join(HERE, "tokens.resolved.css"),
  "/* Generated by mocks/resolve-tokens.mjs — every token as the browser computes it.\n" +
    "   Measurement output, not a source file. Do not import it. */\n\n" +
    block(":root", light) +
    "\n" +
    block(".dark", dark)
);

console.log(
  `WROTE mocks/tokens.resolved.css  light=${Object.keys(light).length} ` +
    `dark=${Object.keys(dark).length} colour tokens ` +
    `(${lightR.skipped.length} non-colour tokens correctly omitted)`
);
