// Message types and utilities
export {
  JSONRPC_VERSION,
  JsonRpcErrorCode,
  type JsonRpcErrorCodeValue,
  type JsonRpcError,
  type JsonRpcRequest,
  type JsonRpcResponse,
  type JsonRpcNotification,
  type JsonRpcMessage,
  isJsonRpcRequest,
  isJsonRpcResponse,
  isJsonRpcNotification,
  // Backward compatibility aliases
  isRequest,
  isResponse,
  isNotification,
  createRequest,
  createResponse,
  createErrorResponse,
  createNotification,
} from './messages.js';

// Command types (Hub -> Agent)
export {
  CommandMethod,
  type CommandMethodValue,
  type SpawnInstanceParams,
  type StopInstanceParams,
  type SendMessageParams,
  type AgentStatusParams,
  type AgentPingParams,
  type SpawnInstanceResult,
  type StopInstanceResult,
  type SendMessageResult,
  type AgentStatusResult,
  type AgentPingResult,
  type CommandParamsMap,
  type CommandResultMap,
  type CommandRequest,
  type SpawnInstanceCommand,
  type StopInstanceCommand,
  type SendMessageCommand,
  type AgentStatusCommand,
  type AgentPingCommand,
} from './commands.js';

// Event types (Agent -> Hub)
export {
  EventMethod,
  type EventMethodValue,
  type InstanceMessageType,
  type InstanceCreatedEvent,
  type InstanceMessageEvent,
  type InstanceStoppedEvent,
  type InstanceStatusChangedEvent,
  type TaskUpdatedEvent,
  type AgentConnectedEvent,
  type AgentDisconnectedEvent,
  type AgentHeartbeatEvent,
  type EventParamsMap,
  type EventNotification,
  type InstanceCreatedNotification,
  type InstanceMessageNotification,
  type InstanceStoppedNotification,
  type InstanceStatusChangedNotification,
  type TaskUpdatedNotification,
  type AgentConnectedNotification,
  type AgentDisconnectedNotification,
  type AgentHeartbeatNotification,
} from './events.js';
